### ISSUE TITLE
Consider moving fedora and solr data out of samvera-mgmt/tmp?

### ISSUE THREAD

**Issue by andrewbenedictwallace** [UCLALibrary/californica#19]
As currently configured, the app stores project data in a `tmp` directory within the main project tree. 

This is bad because the project's root directory is likely to be mounted as a shared directory to the vm, resulting in:
1. Test suite can fail w/ with error `Core 'hydra-test' already exists!` when run with a dirty tmp/ directory.
2. Performance is limited by the underlying mount technology, which at least in the case of Virtualbox shared folders is [very slow](http://mitchellh.com/comparing-filesystem-performance-in-virtual-machines).

Not sure the best alternative - moving the data out of the shared folder is easy, but where we move it to probably depends on individual dev preferences/operating systems...

**Comment by no-reply** [comment]
This seems like a job for `dotenv`? https://github.com/UCLALibrary/samvera-mgmt/blob/master/.env.sample

**Comment by mark-dce** [comment]
If you're using solr_wrapper and fcrepo_wrapper to run you development and test instances of solr and fedora, I think the relevant settings are managed by .solr_wrapper.yml and .fcrepo_wrapper.yml.  If you're running either `bundle exec rails ci` (or `bundle exec rake ci`) or variants of `rake hydra:server` or `rake hydra:test_server` those commands also all invoke solr_wrapper and fcrepo_wrapper to launch instances of solr and fedora.

The test suite should be designed to limit calls to solr and fedora outside of a limited number of integration tests, and I'm guessing it's going to be hard for a single developer to load their system enough to make performance an issue.  So we may want to validate there's a real performance hit here before investing too much time on that account.  The community generally stores development and test content in the application tmp folder to make it easy to purge and reinitialize the local environment.  

We should probably have a larger discussion about how UCLA folks choose to run solr and fedora instances for their local development and test environments.  It sounds like folks might be preferring to use ansible to install more prod-like versions of Solr and Fedora (which isn't a bad idea, but doesn't match general community practice).  If you want to do this, we should probably consider locally overriding `rake ci`, `rake hydra:server`, and `rake hydra:test_server` to use the ansible installed Solr and Fedora instead of the ones managed by solr_wrapper and fcrepo_wrapper.

I've spent a fair amount of time digging into related issues building the VM we use for Samvera Camp and would be happy to spend some time talking or setting up some performance tests if folks want.

**Comment by mark-dce** [comment]
Closing and will open a new ticket if there are specific requirements that arise
