### ISSUE TITLE
Write rails-based task to index to Ursus

### ISSUE THREAD

**Issue by bess** [UCLALibrary/californica#214]
Write a rake task to index LADNN collection into the Ursus solr index

- [x] it cleans out the target solr index before re-indexing everything
- [x] it can be run with a rake task
- [ ] ~it is scheduled in config/schedule.rb~
- [x] the blacklight solr config is set via environment variables

Child of #205

**Comment by val99erie** [comment]
@bess Re: the requirement `it cleans out the target solr index before re-indexing everything`.  If we do a bulk clean and bulk re-index, there will be a period of time where some or all records are missing from the 2nd solr.  Is that acceptable for the first phase?  Or do we need something more sophisticated to make sure deleted records get removed without downtime for other records?

**Comment by bess** [comment]
I think it's fine that there is a period of time when the index is empty, especially for this first phase.

**Comment by val99erie** [comment]
### Evaluation of this option as a possible solution:

This solution as currently implemented (using `ActiveFedora::Base.reindex_everything`) won't work.  Even with a fairly small collection like LADN (less than 6000 records), @little9 reported timeout errors on our testing environment.

We do have the option to change the implementation of `ReindexService` to be more sophisticated.  Instead of using `reindex_everything` (or some other solution that talks to fedora), we could query Californica's solr to get the data we need to update Ursus's solr.  We could also use timestamp comparison to limit the reindexing to only those records that need it.  However, it seems unlikely to me that we could write anything that would be more efficient than solr's own replication logic.

Documentation about the pros and cons of this solution compared to other possible solutions is here:
https://docs.google.com/document/d/1S-9Brc0U-2cRa6UREvAhFPD2_DTxnhx1bnpnVKv2P5s/edit#heading=h.zcp8sf5rlc3k

**Comment by val99erie** [comment]
I did not schedule a cron for this task, since it will just cause timeout errors in our environments.
