### ISSUE TITLE
disable Apache Tika in FITS config on all californica environments

### ISSUE THREAD

**Issue by hardyoyo** [UCLALibrary/californica#344]
This is a known issue for Samvera (see https://github.com/samvera/hydra-file_characterization/issues/25). We have observed that the majority of the CPU usage during ingest processes is in fact running FITS. We have confirmed this default configuration is in place in /opt/fits-1.3.0/xml/fits.xml This means we are currently running Apache Tika against all of our images, and Tika runs OCR. We do not need to be running OCR on our images. Changing this configuration would increase our ingest performance, and spending time running OCR on non-text images is a waste of time and resources.

**Comment by sgurnick** [comment]
I made modifications to our FITS ansible role (https://github.com/UCLALibrary/uclalib_role_fits) to support disabling of the TikaTool library.

I did this differently than how Princeton and UCSD though. They both simply commented out the TikaTool configuration line for the `fits.xml` file. 

Instead of doing that, I turned the `fits.xml` file into a template and created variables that allow us to set which file extensions get excluded from Tika processing. My hope is this will allow us more granular control to use Tika where appropriate for some files, but not others.

@hardyoyo and @bess - please let me know if you have any comments thoughts regarding this.

**Comment by hardyoyo** [comment]
Here's the PR for the change @sgurnick mentioned above: https://github.com/UCLALibrary/uclalib_role_fits/pull/4

My only worry is now you'll have to ensure the fits.xml config stays up to date whenever you upgrade FITS. Which probably isn't a really big deal, but I'd recommend documenting it somewhere.

**Comment by sgurnick** [comment]
I'd imagine we'd have to do similar fits.xml config tracking by doing what Princeton and UCSD are doing by commenting out that line. It is possible that in upgrades to FITS the syntax and other items could change that would make commenting out the Tika line not work as expected.

So overall it seems we are doing kinda the same thing with the same side-effects.

**Comment by hardyoyo** [comment]
You're most likely correct. Using a stale config file is pretty much guaranteed to fail at some point, while a targeted regex is likely to fail... so... it's a quibble. This is fine for now. I trust that you've documented it.

**Comment by sgurnick** [comment]
The changes to the fits.xml config file have been made on each of the californica servers (dev, test, stage, and prod).
