### ISSUE TITLE
Identify the reason an LADNN item has incorrect thumbnail

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/californica#413]
As a user, I want to know why incorrect thumbnails are being displayed:

### Example 1
 http://digital2.library.ucla.edu/Search.do?selectedProjects=all&viewType=1&keyWord=Boy+Scout+Frank+Portune+testifies+for+the+court+regarding+the+discovery+of+the+bodies+of+murdered+children+Jeanette+Stevens+and+Melba+and+Madeline+Everett.+August+12%2C+1937

Search results from DLCS show correct thumbnails which indicate that the data was not bad. (That is, in DLCS we don't have a parade image instead of a courtroom image) 
:http://digital2.library.ucla.edu/Search.do?selectedProjects=all&viewType=1&keyWord=Boy+Scout+Frank+Portune+testifies+for+the+court+regarding+the+discovery+of+the+bodies+of+murdered+children+Jeanette+Stevens+and+Melba+and+Madeline+Everett.+August+12%2C+1937

### Example 2

In Ursus: (search results) https://ursus.library.ucla.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=albert+portune (because thumbnail is not displayed at the item level)
In DLCS: 
http://digital2.library.ucla.edu/viewItem.do?ark=21198/zz0027xhzt

### Example 3
In Ursus: https://ursus.library.ucla.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=Cyclists+compete+in+a+six-day+bicycle+race+at+Pan-Pacific+Auditorium%2C+Los+Angeles%2C+1937 
In DLCS: http://digital2.library.ucla.edu/viewItem.do?ark=21198/zz00288rfb

I discovered several more incorrect thumbnails while reviewing the corrupt tiffs. I did not give all of them as examples here. Not all corrupt tiffs had the wrong thumbnail.

Approval Criteria: 
- [ ] An explanation is provided for why the wrong thumbnail is displaying in ursus for the LADNN item with this local_id and ARK
- [ ] Additional tickets are written (as needed) to either improve error reporting or to address this problem

**Comment by bess** [comment]
@emcaulay I don't think we can really diagnose why corrupt files are behaving in any given way. A file that is corrupt is by definition unpredictable. If this behavior is happening in files that are *not* corrupt, then we should definitely track it down, but afaict that is not the case. I know I'm the one who said that some corrupt files have thumbnails so maybe we should keep the corrupt files around, but if they are the *wrong* thumbnails then that's not behavior that's worth preserving. I would instead suggest that we do as you and Mark had discussed and replace the corrupt file with a placeholder until the photo can be re-scanned.

**Comment by emcaulay** [comment]
So, it's not that these thumbnails are corrupt or weird looking. It's that the wrong thumbnail of a completely good image is displayed instead. This may be a problem that is not worth pursuing, but my current hypothesis is that from the multiple reloads of our LADNN collection into production that some thumbnails from previous loads happened to have the same ID and remained in place from a previous version. I will see if I can test my theory.

**Comment by emcaulay** [comment]
Here's the item with a bad thumbnail in ursus: https://ursus.library.ucla.edu/catalog/3j333234p
in Californica: https://californica.library.ucla.edu/concern/works/3j333234p?locale=en

The thumbnail shows a parade. The real image is supposed to be this one: http://digital2.library.ucla.edu/viewItem.do?ark=21198/zz0027xj0t.

And here's the record for the image that is being displayed erroneous thumbnail: http://digital2.library.ucla.edu/viewItem.do?ark=21198/zz00254hzp

**Comment by bess** [comment]
I have downloaded the TIFF in question and tried to re-create the problem locally. AFAICT, ImageMagick (the progam used to create thumbnails) can't do anything with this TIFF object. It does not write any thumbnail to the derivatives folder when it tries to process this file -- it doesn't even recognize it as an image. On an empty system, the thumnail is a no-image icon, like this:
![no_image_icon.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46e69ba52a8f82ae8ad6b640ab53b2d86b56357c2301a03f32dfa17dbd117e055e5b46a510585615a9f9892af4b035778c5d0effcd7f1d2598694ef1e1c84afd13b0328a488fb7b98f4dc8e93e27e0888d473b0c48.png)

So why, on some systems, would it display an incorrect thumbnail? Here is a theory, which I can't prove, but which I think is the most likely explanation:

1. We imported LADNN on production (and in all our environments) several times.
2. Between imports, we cleaned out the database and Fedora, but we did not clean out the `/opt/derivatives` folder
3. On subsequent imports, because we had cleaned out the database and so Hyrax had no record of what ids it had already used, it happened to generate a unique id for a file that it had already used on a previous import.
4. Because it didn't generate a new thumbnail for the corrupt file, it didn't write over the  previous thumbnail image, and now it has the wrong thumbnail.

In the future we could prevent this by:

1. Ensuring we delete the `/opt/derivatives` folder between ingests if we really want to start over fresh. This is unlikely to come up, however, as we are trying not to clean everything out and start fresh anymore.

OR (This second option is what we're already doing)

2. Do not empty everything out and start over anymore. Instead, when an item is imported it gets a persistent ID that will stick with it even if its metadata is updated. Even if the file is replaced, we won't be cleaning out the database so the system will not re-use identifiers and there will be no chance of associating a previously generated thumbnail.

**Comment by bess** [comment]
Added: If you want to fix this in production someone would need to go in and manually delete the thumbnails for the affected images, or else delete all of `/opt/derivatives` and then run `rake derivatives:regenerate_all`. 

OR

We could wait until we replace the corrupt images with the placeholder image, which will then generate a replacement thumbnail.

**Comment by emcaulay** [comment]
I would like to else delete all of /opt/derivatives and then run rake derivatives:regenerate_all.

I will write a ticket for that. 

I agree with your hypothesis.
