### ISSUE TITLE
Set the collection representative when it's missing

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#428]
**STORY**
As a collection owner, I'd like every collection to have a visual proxy, so that all collections don't look identical in search results.

**DETAILS**
Right now, collections show up in californica (and therefore probably ursus) search results with a generic icon.  The basic idea here is to assign a default representative image based on the first item added to a collection.  Then if someone wants and has time, they can use the californica web UI to pick a more evocative image once more items are added to the collection.  

**ACCEPTANCE**
When a collection has no representative image set, and I add a work to the collection
- [ ] The thumbnail for that work is set as the thumbnail for the collection
- [ ] The representative file (image, audio, document) is set as the representative for the collection

Current State
=========
<img width="471" alt="image" src="https://user-images.githubusercontent.com/3064318/53892449-ef8a5780-3ff1-11e9-8e8c-cf8e0cf6c1fb.png">

**Comment by andrewbenedictwallace** [comment]
This PR does the job, but I got very stuck testing it:
https://github.com/UCLALibrary/californica/pull/477

Putting it back into backlog until someone can help me.

**Comment by andrewbenedictwallace** [comment]
- Doing these is dependent on derivatives having already been generated, so it can't be done in the actor stack. PR #477 sets the collection's thumbnail_id by overriding CreateDerivativesJob instead. (Assuming I'm correct in understanding that the actor stack runs inline, potentially creating offline jobs for sidekiq)
- I can see via the console that collections have a "representative" property, but I haven't seen anything in the GUI that suggests this is used or can be edited. Am I missing something?
- The tests I'd written in PR #477 seems to be failing because it relies on mocked objects (as copied from other tests) that aren't actually in fedora. Fixing it might be a good exercise at some point but probably isn't worth it now because...
- The value of setting the collection thumbnail automatically seems very low. The first image added isn't likely to be the best, and this should be fairly easy to set manually.

Therefore I propose we drop this one. I'm marking it as "wontfix" and closing, but putting in the "review" column to bring this to people's attention.
