### ISSUE TITLE
Update the predicate for Local Identifier

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#435]
**ACCEPTANCE**
- [x] the local_identifier property is stored in the predicate ::RDF::Vocab::Identifiers.local
- [x] local identifiers are not tokenized
- [ ] All data in all environments has been updated to move values to the new location
  - [x] californica-dev
  - [ ] californica-test
  - [ ] californica-stage
  - [ ] californica-prod

Child of #336

**Comment by bess** [comment]
Reloading the metadata for all environments is still in progress (and has to wait for a release), but see below a screenshot of an updated record in californica-dev. 

Note that I had to manually fix the CSV for connell because its local identifier heading was wrong. I opened ticket https://github.com/UCLALibrary/californica/issues/444 to address that problem going forward.

![local_predicate.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46e49b99228ebcb99decbb4aa75ce4916b0a65633b0ba92e7391a172fd1779520a0b4fa849510e44f5a8dc2ba6b76e76835b0decd47f4366846c4ff8e7df46f554f832815d84bfb68b49c5ea3d23ef8a8a4c3e18060ac4.png)
