### ISSUE TITLE
Save new works with ark-based ID

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#492]
**STORY**
As a repository owner, I would like to use ark-based ids for my works and collections, so that I can easily locate items across environments and applications.

**ACCEPTANCE**
- [x] Works and collections must have an ARK (See #456) before saving
- [x] The item's id is assigned based on the ARK - given an ark in the format **ark:/[shoulder]/[blade]** give the item the id **blade-shoulder**
- [x] The registration process also creates a node tree. Given an identifier `ark:/21198/zz00288t76` it should live at `/rest/prod/zz/00/28/8t/zz00288t76-21198` to avoid performance issues from an  unbalanced tree structure in nodeshape.
- [x] Ids are based on the ARK for works created via the UI
- [x] Ids are based on the ARK for collections created via the UI

child of UCLALibrary/ursus#270
requires #456

Update: Active-fedora makes our fedora node tree for us:
```
w = Work.new(id: 'zz00288t76-21198')
2.5.1 :005 > w.uri
 => #<RDF::URI:0x3f8ce0bd26ec URI:http://127.0.0.1:8984/rest/dev/zz/00/28/8t/zz00288t76-21198>
```

**Comment by bess** [comment]
We are going to need to register the shoulder part of the ark as a fedora namespace prefix, following this guide: https://wiki.duraspace.org/display/FEDORA4x/Best+Practices+-+RDF+Namespaces

If we haven't registered the prefix, then when we try to assign an id we get this error:
```
(byebug) object = ActiveFedora::Base.new(:id=>"commonwealth:only_a_test")
*** Ldp::BadRequest Exception: Prefix commonwealth has not been registered
```

**Comment by mark-dce** [comment]
I'm not sure we're going to be able to use the shoulder as a namespace.  It looks to me kinda like namespaces have to begin with an alphabetic character (though the alphabet doesn't have to be English)  https://www.w3.org/TR/turtle/#grammar-production-PN_CHARS_BASE <-- i.e. the first legal character in an RDF prefix name.

**Comment by mark-dce** [comment]
Confirming this: I can reference  a namespace called `ucla101` but not `101` from the fedora console.  This thread was helpful https://groups.google.com/d/msg/fedora-tech/rk8U4KCKWbc/Ybvcf57NlsQJ

**Comment by bess** [comment]
After a conversation with @andrewbenedictwallace I'm not sure we want to use namespaces at all. If we were to use namespaces, they'd need to be registered with every fedora instance we use, including development environments. This thread describes the process: https://wiki.duraspace.org/display/FEDORA4x/Best+Practices+-+RDF+Namespaces

Not only is this labor intensive, it might also be dangerous. If you change a namespace once there is already data in a repository it can lead to data corruption, and several people on the fcrepo slack channel urged us to be very cautious about taking this approach.

Better, perhaps, to use ids like `blade-shoulder` -- we need the blade first, because most of the `shoulder` values will be the same, and we need a balanced node tree for fedora. However, we can't drop the shoulder value entirely, because there are at least two of them and there's a possibility we'd get identifier collision without them.
