### ISSUE TITLE
Something went wrong error when I edit a work in Californica

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#525]
**STEPS TO REPRODUCE**
- [ ] Log in to californica using an admin account - i.e. admin@example.org
- [ ] Search for any results - eg. 'Heavyweight wrestling'
- [ ] Click to view any result in the list - eg. [Wrestling heavyweights Gus Sonnenberg and Baptiste Paul grappling at the Olympic, Los Angeles, 193](https://californica.library.ucla.edu/concern/works/5x21tf59w?locale=en#?c=0&m=0&s=0&cv=0&xywh=-2036%2C-1%2C8270%2C2845)
- [ ] Click on the 'Edit' button

**EXPECTED RESULT**
I should get the edit form

**ACTUAL RESULT**
I get the error "We're sorry, but something went wrong."

**NOTE:** I'm seeing this error both in production ( https://californica.library.ucla.edu ) and test ( https://californica-test.library.ucla.edu )

**Comment by mark-dce** [comment]
FWIW - this only appear to be happening on works created by the importer.  I can edit a work that I have manually created via the UI.

**Comment by bess** [comment]
This is caused by a mis-match between the data in the system and the code. I can verify this problem goes away once the data is re-imported with the latest expected fields. See californica-dev for a place where this is working. It will not be working in other environments until we do a re-import, which I think should wait until after we're ready to assign new primary identifiers.
