### ISSUE TITLE
Confirm LADNN fields to omit from import

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#69]
**ISSUE**
Reviewing the exported csv metdata [box: dlcs-ladnn-2018-08-10.csv](https://ucla.box.com/s/3z7x6humyhdqpeeq4lwe3xgg5qxx004a), a number of fields appear to be very sparsely populated.

Field | Count | Unique Count | Example
-------|--------|------------------|-----------
Item Sequence | 0 | 0 | 
Coverage.spatialLongitude | 1 | 1 | Los Angeles (Calif.)
Rights.servicesContact | 1 | 1 | UCLA Charles E. Young Research Library...
Name.artist | 2 | 2 | Saemundsson, Nina,  $d 1892 - 1965
Name.photographer | 14 | 5 | Acme Newspictures (New York, N.Y.)
Relation.hasVersion | 5 | 1 | Wikipedia submission
Name.architect | 2 | 2 | Kalionzes, Gus $q (William), $d 1910-1984...
Alternate Identifier.url | 2 | 2 | http://www.oac.cdlib.org/findaid/ark:/13030/kt9b69q98h/
Description.adminnote | 1 | 1 | Text from original nitrate sleeve:  County Draft Horses
Alternate Identifier.OPAC | 1 | 1 | 9138

**ACCEPTANCE**
- [ ] Add a ticket for each field that needs to be imported from the above list
- [ ] Confirm that the other of the listed fields can be ignored

**Comment by metaclaudiah** [comment]
Preliminary investigation reveals most of these can be ignored; two need a little more digging. More detailed notes below. 

Coverage.spatialLongitude (1)
That value should be in Coverage.geographic. No need to migrate that field; fixed in DAMS.

Rights.servicesContact (1)
That should be in Rights.rightsHolderContact. No need to migrate; fixed in DAMS 

Name.artist (2)
No need to migrate; I've already fixed so the next time we re-export the metadata it should be clean.

Name.photographer (14/5 unique)
This is sparsely used, because we rarely knew the photographer. I'd like to investigate these further, but leaning towards keeping and if so will provide a predicate. 

Relation.hasVersion (5)
No need to migrate. Not sure what was going on with these!

Name.architect (2)
This one may be worth migrating; I will investigate. 21198/zz0002pf0d has 4 architects responsible for the building depicted; 21198/zz00288d3b is similar but with only one architect. 

Alternate Identifier.url (2)
Should have been .local. No need to migrate; fixed in DAMS.

Description.adminnote (1)
Should have been in Description.caption. No need to migrate; fixed in DAMS.

Alternate Identifier.OPAC
Should have been in .local. No need to migrate; fixed in DAMS.
