### ISSUE TITLE
Add CSV mapping for Rights.copyrightStatus

### ISSUE THREAD

**Issue by no-reply** [UCLALibrary/californica#97]
Given a CSV with a Rights.copyrightStatus column:

 - [ ] importing this CSV creates objects with the values in the `rights` attribute.

Blocked by #109 
Blocked by #243

**Comment by emcaulay** [comment]
FWIW, one our AULs authored the standard copyrightMD, which is where these metadata fields come from. The standard was not widely adopted, but we haven't yet switched to another standard.

**Comment by ksclarke** [comment]
Our spreadsheet https://docs.google.com/spreadsheets/d/1muoNt40y7nKPlthOr_CwuvvXdQLM2uYhEu55GXhASnU/edit#gid=875035976 says to use 'rights_statement' instead of 'rights' (like in this ticket), but this may be a part of a larger question that https://github.com/UCLALibrary/californica/issues/109 addresses. For now, we'll mark 109 as a blocker for this one.

**Comment by ksclarke** [comment]
Not clear if this is the same thing or a different thing from the rights_statement in the following, but dropping the link in here so we can get more clarity: https://github.com/samvera/hyrax/blob/master/app/models/concerns/hyrax/basic_metadata.rb

**Comment by val99erie** [comment]
And here is where the drop-down options for the `rights_statement` are configured for Californica:
`https://github.com/UCLALibrary/californica/blob/master/config/authorities/rights_statements.yml`
